services:
  storage:
    image: redis
  counter:
    build: ./counter
    ports:
      - 80:3000

    environment:
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    links:
      - storage
  main:
    build: .
    ports:
      - 81:3000
<<<<<<< HEAD
    depends_on:
      - counter
    links:
      - counter
=======
>>>>>>> 066b672389fbf6d9ddec6305c106943836650c52
